### ISSUE TITLE
Can the source, project for vertx-swagger be made available

### ISSUE THREAD

**Issue by apatrida** [zalando/krueger-cockpit#1]
This project references a `jar` in the `lib/` directory for vert-x + swagger.  Can you make this code available?

I am adding support to [Kovert (for Kotlin)](https://github.com/kohesive/kovert) to do two things:
1.  generate a swagger definition given all bound controllers, using Kotlin reflection
2.  verify that any methods bound in a Kovert controller make a loaded swagger definition (run as unit test)

I think all of this would be useful to krueger-cockpit project.

**Comment by hjacobs** [comment]
:+1: for making the source of JARs in lib transparent.

**Comment by peletomi** [comment]
I have made the repo public (sorry forgot after releasing). You find it here: https://github.com/zalando/axiom-web

We don't have nice kotlin bindings yet. But I would like to have some, because right now it is nicer to use the lib from java.

**Comment by apatrida** [comment]
thanks!  Will see how this can merge into Kovert.
